#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set network.CaptivePortal=interface
	set network.CaptivePortal.proto='autoip'
	set network.CaptivePortal.device='br-captive'
	set network.device_CaptivePortal.name='br-captive'
	set network.device_CaptivePortal.type='bridge'
	set network.device_CaptivePortal.bridge_empty='1'
	commit network
EOF

