#!/bin/sh

if ! uci -q show watchcat.@watchcat[0]
then
	uci set watchcat.watchcat[0]='watchcat'
	uci set watchcat.watchcat[0].addressfamily='ipv4'
	uci set watchcat.watchcat[0].interface='@ZeroTier'
	uci set watchcat.watchcat[0].mode='run_script'
	uci set watchcat.watchcat[0].period='3m'
	uci set watchcat.watchcat[0].pinghosts='10.27.253.1'
	uci set	watchcat.watchcat[0].pingperiod='30s'
	uci set watchcat.watchcat[0].pingsize='standard'
	uci set watchcat.watchcat[0].script='/root/restart-zerotier.sh'
	uci commit watchcat
fi
