#!/bin/sh

if ! uci -q show dhcp.@dnsmasq[0].notinterface
then
    uci add_list dhcp.@dnsmasq[0].notinterface='pppoe-wan'
    uci commit dhcp
fi

if ! uci -q show dhcp.@dnsmasq[0].server
then
    uci add_list dhcp.@dnsmasq[0].server='/nnxx/141.95.18.146' '/nnxx/51.178.46.85' '8.8.8.8' '2001:4860:4860::8888'
    uci commit dhcp
fi
